version: '3.8'
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_container
    environment:
      - SA_PASSWORD=Password123$ # User: "SA"
      - ACCEPT_EULA=Y
    volumes:
      - sql_data:/var/opt/mssql
    ports:
      - "1433:1433" # Default port for SQL Server

volumes:
  sql_data:
    driver: local

